#!url=https://raw.githubusercontent.com/yuhan5187/shadowrocket-rules/refs/heads/master/sr_gang_list.module
#!name=gang-rule
#!desc=Description Here


[Rule]
RULE-SET,https://whatshub.top/rule/Netflix.list,🎬 NETFLIX
RULE-SET,https://whatshub.top/rule/YouTube.list,📽️ YOUTUBE
RULE-SET,https://whatshub.top/rule/GoogleVoice.list,🇺🇸 美国节点
RULE-SET,https://whatshub.top/rule/OpenAI.list,🤖 OpenAi
RULE-SET,https://whatshub.top/rule/Speedtest.list,PROXY
RULE-SET,https://whatshub.top/rule/AppleMusic.list,DIRECT



DOMAIN-SUFFIX,unogs.com,🎬 NETFLIX

DOMAIN-SUFFIX,speedtest.net,PROXY
DOMAIN-SUFFIX,nodeseek.com,PROXY
DOMAIN-SUFFIX,sav.com,PROXY
DOMAIN-SUFFIX,cdnst.net,PROXY
DOMAIN-SUFFIX,whatismyipaddress.com,PROXY
DOMAIN-SUFFIX,hqporner.com,PROXY
DOMAIN-SUFFIX,bigcdn.cc,PROXY
DOMAIN-SUFFIX,hjd2048.com,PROXY
DOMAIN-SUFFIX,plugin-alliance.com,PROXY
DOMAIN-SUFFIX,waves.com,PROXY
DOMAIN-SUFFIX,obdev.at,PROXY



DOMAIN-SUFFIX,w3schools.com,DIRECT
DOMAIN-SUFFIX,itdog.cn,DIRECT
DOMAIN-SUFFIX,miguoyun.cn,DIRECT
DOMAIN-SUFFIX,miuicloud.com,DIRECT
DOMAIN-SUFFIX,97.gs,DIRECT
