#!url=https://raw.githubusercontent.com/yuhan5187/shadowrocket-rules/refs/heads/master/sr_gang_list.module
#!name=gang-rule
#!desc=Description Here


[Proxy Group]

🤖 OpenAi = select,🇺🇸 美国节点,🇭🇰 香港节点,🇸🇬 新加坡节点,policy-select-name=🇸🇬 新加坡节点

[Rule]
RULE-SET,https://whatshub.top/rule/Netflix.list,🎬 NETFLIX
RULE-SET,https://whatshub.top/rule/YouTube.list,📽️ YOUTUBE
RULE-SET,https://whatshub.top/rule/GoogleVoice.list,🇺🇸 美国节点
RULE-SET,https://whatshub.top/rule/OpenAI.list,🤖 OpenAi
RULE-SET,https://whatshub.top/rule/Speedtest.list,PROXY

DOMAIN-SUFFIX,speedtest.net,PROXY
DOMAIN-SUFFIX,nodeseek.com,PROXY
DOMAIN-SUFFIX,w3schools.com,DIRECT
DOMAIN-SUFFIX,sav.com,PROXY
DOMAIN-SUFFIX,cdnst.net,PROXY
