#!url=https://raw.githubusercontent.com/yuhan5187/shadowrocket-rules/refs/heads/master/sr_gang_list.module
#!name=gang-rule
#!desc=Description Here

[Rule]
RULE-SET,https://whatshub.top/rule/Netflix.list,🎬 NETFLIX
RULE-SET,https://whatshub.top/rule/YouTube.list,📽️ YOUTUBE
RULE-SET,https://whatshub.top/rule/GoogleVoice.list,🇺🇸 美国节点
RULE-SET,https://whatshub.top/rule/Speedtest.list,PROXY

DOMAIN-SUFFIX,speedtest.net,PROXY
DOMAIN-SUFFIX,nodeseek.com,PROXY
DOMAIN-SUFFIX,w3schools.com,DIRECT
DOMAIN-SUFFIX,sav.com,PROXY
